# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blog.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "blog.ReadAllRequest" do
  end
  add_message "blog.ReadAllResponse" do
    repeated :posts, :message, 1, "blog.Post"
  end
  add_message "blog.ReadByIdRequest" do
    optional :id, :int32, 1
  end
  add_message "blog.ReadByIdResponse" do
    optional :post, :message, 1, "blog.Post"
  end
  add_message "blog.CreateRequest" do
    optional :title, :string, 1
    optional :body, :string, 2
  end
  add_message "blog.CreateResponse" do
    optional :post, :message, 1, "blog.Post"
  end
  add_message "blog.Post" do
    optional :id, :int32, 1
    optional :title, :string, 2
    optional :body, :string, 3
  end
end

module Blog
  ReadAllRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("blog.ReadAllRequest").msgclass
  ReadAllResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("blog.ReadAllResponse").msgclass
  ReadByIdRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("blog.ReadByIdRequest").msgclass
  ReadByIdResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("blog.ReadByIdResponse").msgclass
  CreateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("blog.CreateRequest").msgclass
  CreateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("blog.CreateResponse").msgclass
  Post = Google::Protobuf::DescriptorPool.generated_pool.lookup("blog.Post").msgclass
end
